site_name: Hands-on with the ORCID API
theme: material
extra_css: [css/theme_override.css]
extra:
  palette:
    primary: 'grey'
  font:
    text: 'Noto Sans'
  logo:
      icon:
        'docs/images/id-icon.svg'
nav:
    - 1. Introduction: index.md
    - 2. Set up the Sandbox: sandbox.md
    - 3. GET&#58; authenticated iDs &amp; permission: get.md
    - 4. READ&#58; the record: read.md
    - 5. POST&#58; an affiliation: post.md
    - 6. PUT&#58; Update an affiliation: put.md
    - 7. DISPLAY&#58; Presenting ORCID in your system: display.md
    - 8. RESOURCES: resources.md
    - 9. Other methods for getting authorised iDs: Other_methods_for_getting_authorised_iDs.md
